// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  adminSidebar: [
    {
      type: "autogenerated",
      dirName: "admin-setup"
    }],
  webSidebar: [{
    type: "autogenerated",
    dirName: "website-setup"
  }],
  appSidebar: [{
    type: "autogenerated",
    dirName: "app-setup"
  }],
  featuresSidebar: [{
    type: "autogenerated",
    dirName: "features"
  }],
  changelogSidebar: [{
    type: "autogenerated",
    dirName: "changelog"
  }],
  supportSidebar: [{
    type: "autogenerated",
    dirName: "community-support"
  }],
};

export default sidebars;
